# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Vincentqyw"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Quantitative Trading": 
        filters: ["Quantitative Trading", "Algorithmic Trading", "Automated Trading"]
    "Financial Time Series":
        filters: ["Financial Time Series", "Time Series Analysis", "Market Prediction"]
    "Risk Management":
        filters: ["Risk Management", "Portfolio Optimization", "Risk Assessment"]
    "Machine Learning in Finance":
        filters: ["Machine Learning", "Deep Learning", "AI in Finance", "Predictive Modeling"]
    "Sentiment Analysis":
        filters: ["Sentiment Analysis", "Market Sentiment", "News Sentiment"]
    "High-Frequency Trading":
        filters: ["High-Frequency Trading", "HFT", "Market Microstructure"]
    "Trading Strategies":
        filters: ["Trading Strategies", "Investment Strategies", "Quantitative Strategies"]


